// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Block is the predicate function for block builders.
type Block func(*sql.Selector)

// Part is the predicate function for part builders.
type Part func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)

// Work is the predicate function for work builders.
type Work func(*sql.Selector)
