// Code generated by ent, DO NOT EDIT.

package ent

import (
	"graphql-test-api/ent/block"
	"graphql-test-api/ent/schema"
	"graphql-test-api/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blockFields := schema.Block{}.Fields()
	_ = blockFields
	// blockDescAuthorID is the schema descriptor for author_id field.
	blockDescAuthorID := blockFields[1].Descriptor()
	// block.DefaultAuthorID holds the default value on creation for the author_id field.
	block.DefaultAuthorID = blockDescAuthorID.Default.(string)
	// blockDescSpeed is the schema descriptor for speed field.
	blockDescSpeed := blockFields[2].Descriptor()
	// block.DefaultSpeed holds the default value on creation for the speed field.
	block.DefaultSpeed = blockDescSpeed.Default.(float64)
	// blockDescSpeaker is the schema descriptor for speaker field.
	blockDescSpeaker := blockFields[3].Descriptor()
	// block.DefaultSpeaker holds the default value on creation for the speaker field.
	block.DefaultSpeaker = blockDescSpeaker.Default.(string)
	// blockDescVolume is the schema descriptor for volume field.
	blockDescVolume := blockFields[4].Descriptor()
	// block.DefaultVolume holds the default value on creation for the volume field.
	block.DefaultVolume = blockDescVolume.Default.(float64)
	// blockDescPitch is the schema descriptor for pitch field.
	blockDescPitch := blockFields[5].Descriptor()
	// block.DefaultPitch holds the default value on creation for the pitch field.
	block.DefaultPitch = blockDescPitch.Default.(int)
	// blockDescTexts is the schema descriptor for texts field.
	blockDescTexts := blockFields[6].Descriptor()
	// block.DefaultTexts holds the default value on creation for the texts field.
	block.DefaultTexts = blockDescTexts.Default.(string)
	// blockDescDuration is the schema descriptor for duration field.
	blockDescDuration := blockFields[7].Descriptor()
	// block.DefaultDuration holds the default value on creation for the duration field.
	block.DefaultDuration = blockDescDuration.Default.(int)
	// blockDescID is the schema descriptor for id field.
	blockDescID := blockFields[0].Descriptor()
	// block.DefaultID holds the default value on creation for the id field.
	block.DefaultID = blockDescID.Default.(func() string)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescStripeID is the schema descriptor for stripe_id field.
	userDescStripeID := userFields[2].Descriptor()
	// user.DefaultStripeID holds the default value on creation for the stripe_id field.
	user.DefaultStripeID = userDescStripeID.Default.(string)
	// userDescPoint is the schema descriptor for point field.
	userDescPoint := userFields[3].Descriptor()
	// user.DefaultPoint holds the default value on creation for the point field.
	user.DefaultPoint = userDescPoint.Default.(int)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() string)
}
