package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"
	"graphql-test-api/ent"
	"graphql-test-api/ent/part"
	"graphql-test-api/ent/user"
	"graphql-test-api/ent/work"
)

// GetUserByID is the resolver for the getUserById field.
func (r *queryResolver) GetUserByID(ctx context.Context, id string) (*ent.User, error) {
	return r.Client.User.Query().Where(user.IDEQ(id)).First(ctx)
}

// GetWorkByID is the resolver for the getWorkById field.
func (r *queryResolver) GetWorkByID(ctx context.Context, id string) (*ent.Work, error) {
	return r.Client.Work.Query().Where(work.IDEQ(id)).First(ctx)
}

// GetUserByGoogleID is the resolver for the getUserByGoogleId field.
func (r *queryResolver) GetUserByGoogleID(ctx context.Context, googleID string) (*ent.User, error) {
	return r.Client.User.Query().Where(user.GoogleIDEQ(googleID)).First(ctx)
}

// GetPartByID is the resolver for the getPartById field.
func (r *queryResolver) GetPartByID(ctx context.Context, partID string) (*ent.Part, error) {
	return r.Client.Part.Query().Where(part.IDEQ(partID)).First(ctx)
}
